"""add versioned source artifacts

Revision ID: 04dfa7dfac0c
Revises: 8d3b0f5e2a71
Create Date: 2026-08-22 23:45:44.272361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04dfa7dfac0c'
down_revision = '8d3b0f5e2a71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('content_checksum', sa.String(length=64), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'version', name='uq_source_artifact_version')
    )
    with op.batch_alter_table('data_source_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_source_artifacts_content_checksum'), ['content_checksum'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_source_artifacts_data_source_id'), ['data_source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_source_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_source_artifacts_data_source_id'))
        batch_op.drop_index(batch_op.f('ix_data_source_artifacts_content_checksum'))

    op.drop_table('data_source_artifacts')
    # ### end Alembic commands ###
