"""add source synchronization metadata

Revision ID: 229ebea0961f
Revises: e832a20e0c86
Create Date: 2026-08-22 22:55:30.073603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229ebea0961f'
down_revision = 'e832a20e0c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('schema_json', sa.JSON(), nullable=False),
    sa.Column('content_checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'version', name='uq_data_snapshot_source_version')
    )
    with op.batch_alter_table('data_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_snapshots_data_source_id'), ['data_source_id'], unique=False)

    op.create_table('data_source_sync_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('refresh_mode', sa.String(length=16), nullable=False),
    sa.Column('max_records', sa.Integer(), nullable=False),
    sa.Column('lock_token', sa.String(length=36), nullable=True),
    sa.Column('lock_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_source_sync_policies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_source_sync_policies_data_source_id'), ['data_source_id'], unique=True)

    op.create_table('data_source_sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('records_fetched', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['snapshot_id'], ['data_snapshots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'idempotency_key', name='uq_source_sync_idempotency')
    )
    with op.batch_alter_table('data_source_sync_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_source_sync_runs_data_source_id'), ['data_source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_source_sync_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_source_sync_runs_data_source_id'))

    op.drop_table('data_source_sync_runs')
    with op.batch_alter_table('data_source_sync_policies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_source_sync_policies_data_source_id'))

    op.drop_table('data_source_sync_policies')
    with op.batch_alter_table('data_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_snapshots_data_source_id'))

    op.drop_table('data_snapshots')
    # ### end Alembic commands ###
