"""add federated rule sources

Revision ID: 86b815857fd1
Revises: 04dfa7dfac0c
Create Date: 2026-08-23 00:44:03.673079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b815857fd1'
down_revision = '04dfa7dfac0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('join_to_alias', sa.String(length=64), nullable=True),
    sa.Column('left_field', sa.String(length=128), nullable=True),
    sa.Column('right_field', sa.String(length=128), nullable=True),
    sa.Column('join_type', sa.String(length=16), nullable=False),
    sa.Column('join_operator', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("join_operator IN ('eq', 'casefold_eq', 'numeric_eq')", name='ck_rule_source_join_operator'),
    sa.CheckConstraint("join_type IN ('inner', 'left')", name='ck_rule_source_join_type'),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['audit_rules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'alias', name='uq_rule_data_source_alias'),
    sa.UniqueConstraint('rule_id', 'data_source_id', name='uq_rule_data_source_source')
    )
    with op.batch_alter_table('rule_data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_data_sources_data_source_id'), ['data_source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_data_sources_rule_id'), ['rule_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule_data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_data_sources_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rule_data_sources_data_source_id'))

    op.drop_table('rule_data_sources')
    # ### end Alembic commands ###
