"""add data mapping and quality checks

Revision ID: e832a20e0c86
Revises: 6f9f18d41e75
Create Date: 2026-08-22 22:39:42.246262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e832a20e0c86'
down_revision = '6f9f18d41e75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('source_column', sa.String(length=128), nullable=False),
    sa.Column('target_field', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=24), nullable=False),
    sa.Column('transformation', sa.String(length=24), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'source_column', 'target_field', name='uq_field_mapping_source_target')
    )
    with op.batch_alter_table('field_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_field_mappings_data_source_id'), ['data_source_id'], unique=False)

    op.create_table('quality_checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('check_type', sa.String(length=32), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('data_source_id', 'name', name='uq_quality_check_source_name')
    )
    with op.batch_alter_table('quality_checks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_checks_data_source_id'), ['data_source_id'], unique=False)

    op.create_table('quality_check_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quality_check_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('scanned_records', sa.Integer(), nullable=False),
    sa.Column('failed_records', sa.Integer(), nullable=False),
    sa.Column('pass_rate', sa.Float(), nullable=False),
    sa.Column('failure_sample', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quality_check_id'], ['quality_checks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_check_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_check_runs_quality_check_id'), ['quality_check_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quality_check_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_check_runs_quality_check_id'))

    op.drop_table('quality_check_runs')
    with op.batch_alter_table('quality_checks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_checks_data_source_id'))

    op.drop_table('quality_checks')
    with op.batch_alter_table('field_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_field_mappings_data_source_id'))

    op.drop_table('field_mappings')
    # ### end Alembic commands ###
